apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-consumer
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: binance-consumer
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: LOG_LEVEL
          value: "info"
      # Production-specific settings
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - binance-consumer
              topologyKey: kubernetes.io/hostname