name: 'Build Docker Image'
description: 'Builds the Docker image for BinanceConsumer'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build -t ${{ inputs.image_name }}:${{ inputs.tag }} .
      shell: bash
inputs:
  image_name:
    description: 'Name of the Docker image'
    required: true
  tag:
    description: 'Tag for the Docker image'
    required: true
